config/routes.rb
Rails.application.routes.draw do
  get 'app_manager/show'

  get 'app_manager/index'

  get 'app_manager/destroy'

  get 'employers/create'

  get 'test_tasks/main' => 'test_tasks#main'
  get 'test_tasks/signed' => 'test_tasks#signed'

  get 'sessions/new'

  get 'users/new'

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"

  get "administration" => "app_manager#index"
  

  get "log_employer" => "employers#new", :as => "log_employer"
  get "wyloguj" => "employers#destroy", :as => "wyloguj"

  root :to => "users#welcome"
  resources :users
  resources :sessions
  resources :employers 

  resources :password_resets, only: [ :new, :create]

  get '/password_resets/edit' => 'password_resets#edit', as: :edit_password_reset
  put '/password_resets/' => 'password_resets#update', as: :password_reset

end

app/controllers/app_manager_controller.rb
class AppManagerController < ApplicationController
	before_action :logged_in_employer
	

  def show
  end

  def index
  	@users = User.all
  end

  def destroy
  	# flash.now.alert = "Niepoprawne hasło/login"
  end

	# Confirms a logged-in user.
	def logged_in_employer
	  unless logged_employer_in?
	    flash[:danger] = "Proszę się zalogować."
	    redirect_to url_for(controller: 'employers', action: 'create')
	  end
	end
end

app/helpers/app_manager_helper.rb
module AppManagerHelper
end

app/views/app_manager/destroy.html.erb
<h1>AppManager#destroy</h1>
<p>Find me in app/views/app_manager/destroy.html.erb</p>

app/views/app_manager/index.html.erb
Logged in as <%= current_employer.login %>.
<%= link_to "Wyloguj się!", wyloguj_path %>

<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>

<% @users.each do |user, index| %>
    <tr>
    <p> User number: <%= user.id %> <br>
      <td>Nick: <%= user.email %></td><br>
      <td>Password_hash: <%= user.password_hash %></td><br>
      <td>Adres email: <%= user.mail %></td><br>
      <%= link_to "delete", user, method: :delete,
                                data: { confirm: "You sure?" } %>
    </tr>
    <br>
  <% end %>

app/views/app_manager/show.html.erb
<h1>AppManager#show</h1>
<p>Find me in app/views/app_manager/show.html.erb</p>