config/routes.rb
Rails.application.routes.draw do
  get 'app_manager/show'

  get 'app_manager/index'

  get 'app_manager/destroy'

  get 'employers/create'

  get 'test_tasks/main' => 'test_tasks#main'
  get 'test_tasks/signed' => 'test_tasks#signed'

  get 'sessions/new'

  get 'users/new'

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"

  get "administration" => "app_manager#index"
  

  get "log_employer" => "employers#new", :as => "log_employer"
  get "wyloguj" => "employers#destroy", :as => "wyloguj"

  root :to => "users#welcome"
  resources :users
  resources :sessions
  resources :employers 

  resources :password_resets, only: [ :new, :create]

  get '/password_resets/edit' => 'password_resets#edit', as: :edit_password_reset
  put '/password_resets/' => 'password_resets#update', as: :password_reset

end

app/controllers/test_tasks_controller.rb
class TestTasksController < ApplicationController
	before_action :logged_in_user

	def main
	end

	def signed
	end

	def administrator
	end

  # Confirms a logged-in user.
	def logged_in_user
	  unless logged_in?
	    flash[:danger] = "Proszę się zalogować."
	    redirect_to url_for(controller: 'sessions', action: 'new')
	  end
	end
end

app/helpers/test_tasks_helper.rb
module TestTasksHelper
	   # Returns true if the user is logged in, false otherwise.
   def logged_in?
       !current_user.nil?
   end

   # Confirms a logged-in user.
   def logged_in_user
      unless logged_in?
         flash[:danger] = "Please log in."
         redirect_to url_for(controller: 'sessions_controller', action: 'new')
      end
   end
end

app/views/test_tasks/main.html.erb
<div id="user_nav">
  <% if current_user %>
    Jesteś zalogowany jako: <%= current_user.email %>.
    <%= link_to "Wyloguj się!", log_out_path %>
    <%= link_to "Wyświetl Profil", current_user %>
  <% else %>
    <%= link_to "Załóż konto!", sign_up_path %> or
    <%= link_to "Zaloguj się tu!", log_in_path %>
  <% end %>
</div>

<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>
<p>Witaj użytkowniku!</p>

app/views/test_tasks/signed.html.erb
<div id="user_nav">
  <% if current_user %>
    Logged in as <%= current_user.email %>.
    <%= link_to "Wyloguj się!", log_out_path %>
  <% else %>
    <%= link_to "Załóż konto!", sign_up_path %> or
    <%= link_to "Zaloguj się tu!", log_in_path %>
  <% end %>
</div>

<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>
<h1>Proszę się zalogować!!!</h1>