config/routes.rb
Rails.application.routes.draw do
  get 'app_manager/show'

  get 'app_manager/index'

  get 'app_manager/destroy'

  get 'employers/create'

  get 'test_tasks/main' => 'test_tasks#main'
  get 'test_tasks/signed' => 'test_tasks#signed'

  get 'sessions/new'

  get 'users/new'

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"

  get "administration" => "app_manager#index"
  

  get "log_employer" => "employers#new", :as => "log_employer"
  get "wyloguj" => "employers#destroy", :as => "wyloguj"

  root :to => "users#welcome"
  resources :users
  resources :sessions
  resources :employers 

  resources :password_resets, only: [ :new, :create]

  get '/password_resets/edit' => 'password_resets#edit', as: :edit_password_reset
  put '/password_resets/' => 'password_resets#update', as: :password_reset

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation, :mail
  
  attr_accessor :password
  before_save :encrypt_password
  
  VALID_MAIL_REGEX = /\A[\w+\-.]+@[a-z\-.]+\.[a-z]+\z/i
  validates_confirmation_of :password
  # validates_presence_of :password, :on => :create
  # validates_presence_of :email
  validates_uniqueness_of :email, message: 'W bazie istnieje już użytkownik z podanym loginem'

  validates :mail, presence: true, length: { maximum: 255 },
                    format: { with: VALID_MAIL_REGEX, :message => "Niepoprawny e-mail. Przykład poprawnego: foo@bar.com" },
                    uniqueness: { case_sensitive: false, message: 'W bazie istnieje już użytkownik z podanym adresem email' }
  validates :password, presence: { in: [true], message: 'Hasło musi mieć minimum 6 znaków'}, length: { minimum: 6 }, allow_nil: true

  def deliver_password_reset_instructions
    self.perishable_token = get_reset_token
    save(validate: false)

    PasswordResetNotifier.password_reset_instructions(self).deliver_now
  end

  def get_reset_token
    SecureRandom.urlsafe_base64
  end
  
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :logged_in_user, only: [:edit, :update, :show]
	before_action :correct_user,   only: [:edit, :update]

	def welcome
	end

      def show
	    @user = User.find(params[:id])
	  end

	def new
  # 	  if logged_in?
		# redirect_to url_for(controller: 'test_tasks', action: 'main')
	 #  end
	  @user = User.new
	end

	  def edit
	    @user = User.find(params[:id])
	  end

	  def update
	    @user = User.find(params[:id])
	    if @user.update_attributes(user_params)
	        flash[:success] = "Profile updated"
      		redirect_to url_for(controller: 'test_tasks', action: 'main')
	    else
	    	flash[:success] = "Profile not updated"
	      render 'edit'
	    end
	  end

	# def index
	# 	@users = User.all
	# end

	def destroy
		User.find(params[:id]).destroy
    	flash[:success] = "User deleted"
  		redirect_to url_for(controller: 'app_manager', action: 'index')
  	end

	def create
	  @user = User.new(params[:user])
	  if @user.save
	    redirect_to url_for(controller: 'test_tasks', action: 'signed'), :notice => "Poprawnie zarejestrowano!"
	  else
	    render "new"
	  end
	end

	def logged_in_user
	  unless logged_in?
	    flash[:danger] = "Proszę się zalogować."
	    redirect_to url_for(controller: 'sessions', action: 'new')
	  end
	end

	private

	    def user_params
	      params.require(:user).permit(:email, :password,
	                                   :password_confirmation)
	    end

        # Confirms the correct user.
	    def correct_user
	      @user = User.find(params[:id])
	      redirect_to url_for(controller: 'test_tasks', action: 'main') unless @user == current_user 
	    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h1>Update your profile</h1>
<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      
      <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Dane wprowadzone do formularza są niepoprawne</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
      
      <%= f.label :login %>
      <%= f.text_field :email, class: 'form-control' %>

      <%= f.label :password, "Hasło" %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Potwierdź nowe hasło" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Zapisz zmiany", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div id="user_nav">
    <p>Posiadasz już konto?</p><br>
    <%= link_to "Zaloguj się tu!", log_in_path %>
</div>

<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>

<h1>Rejestracja</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Dane wprowadzone do formularza są niepoprawne</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= f.label :Login %><br />
      <%= f.text_field :email, class: "form-control" %><br />

      <%= f.label :Email %><br />
      <%= f.text_field :mail, class: "form-control" %><br />

      <%= f.label :Hasło %><br />
      <%= f.password_field :password, class: "form-control" %><br />

      <%= f.label :Powtórz_hasło%><br />
      <%= f.password_field :password_confirmation, class: "form-control" %><br />

      <%= f.submit "Zarejestruj się!", class: "btn btn-primary" %>
      </div>
  </div>
<% end %>

app/views/users/show.html.erb
<h1>Profil użytkownika "<%= current_user.email %>"</h1>

<%= link_to "Zmień hasło", { :controller => "users", :action => "edit"}, class: "btn btn-danger" %><br>
<%= link_to "Powrót do strony profilowej", { :controller => "test_tasks", :action => "main"}, class: "btn btn-danger" %>

app/views/users/welcome.html.erb
<h1>Witaj w teście kandydata na specjalistę IT</h1>

<%= link_to "Jestem kandydatem", log_in_path, class: "btn btn-success" %> <br>
<%= link_to "Jestem pracodawcą", log_employer_path, class: "btn btn-success" %>